ReservationApp/ReservationApp/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReservationApp.Data;
using ReservationApp.Models;

namespace ReservationApp.Controllers
{
    public class ReservationsController : Controller
    {
        public int reserveValid = 0;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        public ReservationsController(UserManager<IdentityUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }
        

        // GET: Reservations
        public async Task<ActionResult> Index()
        {
            
            if (User.IsInRole("Student"))
            {
                IdentityUser user = await _userManager.FindByEmailAsync(User.Identity.Name);
                var reservations = _context.Reservation.Include(r => r.TypeReservation).ToList().Where(r => r.UserId == user.Id).OrderBy(r => r.Status); // include pour afficher le nom de type d'objet type
                return View(reservations);
            }
            else
            {
                var reservations = _context.Reservation.Include(r => r.TypeReservation).Include(r => r.User).ToList().OrderBy(r => r.Status);
                return View(reservations);
            }
        }

        // GET: Reservations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // GET: Reservations/Create
        public IActionResult Create()
        {

            var reservation = new Reservation();
            ViewBag.UserId = _userManager.GetUserId(HttpContext.User);  // recuperer id de user en connection pour remplir la valeur de UserId comme proprietaire de cette reservation crée
            IEnumerable<TypeReservation> types = _context.TypeReservation.ToList(); // pour charger les types et les afficher sur input select
            ViewBag.Types = types;

            return View(reservation);
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create( Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reservation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
        

            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation.FindAsync(id);
            if (reservation == null)
            {
                return NotFound();
            }
            if (User.IsInRole("Student"))
            {
                ViewBag.UserId = _userManager.GetUserId(HttpContext.User);  // recuperer id de user en connection pour remplir la valeur de UserId comme proprietaire de cette reservation crée
                IEnumerable<TypeReservation> types = _context.TypeReservation.ToList(); // pour charger les types et les afficher sur input select
                ViewBag.Types = types;
                return View("Edit", reservation);
            }
            else
            {
                ViewBag.UserId = _userManager.GetUserId(HttpContext.User);  // recuperer id de user en connection pour remplir la valeur de UserId comme proprietaire de cette reservation crée
                IEnumerable<TypeReservation> types = _context.TypeReservation.ToList(); // pour charger les types et les afficher sur input select
                ViewBag.Types = types;
                return View("EditA", reservation);
            }
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  Reservation reservation)
        {
            if (id != reservation.Id)
            {
                return NotFound();
            }

            var idUser = reservation.UserId;
            //ApplicationUsers user = await userManager.FindByIdAsync(idUser);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reservation);
                    //if (reservation.Status == Status.Accepted)
                    //{
                    //    reservation.User.counter++;
                    //    await _context.SaveChangesAsync();
                    //}
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservationExists(reservation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //public IActionResult Status(int Id)
                //{

                //    var reservation = Db.Reservations.Include(x => x.utitlisateur).FirstOrDefault(x => x.id_reservation == id);
                //    reservation.Status = "Approve";
                //    reservation.utitlisateur.Counter++;
                //    _Db.Reservations.Update(reservation);
                //    _Db.SaveChanges();

                //    return RedirectToAction("Index");
                //}
                return RedirectToAction(nameof(Index));
            }

            ViewBag.UserId = _userManager.GetUserId(HttpContext.User);  // recuperer id de user en connection pour remplir la valeur de UserId comme proprietaire de cette reservation crée
            IEnumerable<TypeReservation> types = _context.TypeReservation.ToList(); // pour charger les types et les afficher sur input select
            ViewBag.Types = types;
            return View(reservation);

        }

        // GET: Reservations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reservation = await _context.Reservation.FindAsync(id);
            _context.Reservation.Remove(reservation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
            return _context.Reservation.Any(e => e.Id == id);
        }
    }
}

ReservationApp/ReservationApp/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReservationApp.Models;
using ReservationApp.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReservationApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<IdentityUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;

        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View(new IdentityRole());
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            await _roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            
            Role model = new Role()
            {
                Id = role.Id,
                Name = role.Name,
                Users = new List<string>()
            };

            foreach (IdentityUser user in  _userManager.Users.ToList()) // userManager.Users is not awaitble so change to (await userManager.Users.ToListAsync())
            {
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }
            return View(model);
        }



        [HttpPost]
        public async Task<IActionResult> Edit(Role model)
        {
            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByIdAsync(model.Id);
               
                role.Name = model.Name;

                IdentityResult result = await _roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);

        }

        [HttpGet]
        public IActionResult Delete()
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);

            if (!(role is null))
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);

                if (!result.Succeeded)
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            else
            {
                return View("../Error/NotFound", $"The role Id : {id} cannot be found");

            }
            return RedirectToAction("Index");
        }

       
        [HttpGet]
        public async Task<IActionResult> EditUsersRole(string roleId)
        {
            if (string.IsNullOrEmpty(roleId))
            {
                return View("../Error/NotFound", $"The role must be exist and not empty in Url");

            }
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
            {
                return View("../Error/NotFound", $"The role Id : {role.Id} cannot be found");
            }

            var Models = new List<EditUsersRoleViewModel>(); 

            foreach (var user in await _userManager.Users.ToListAsync())
            {
                EditUsersRoleViewModel model = new EditUsersRoleViewModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    //IsSelected = false
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    model.IsSelected = true;
                }
                else
                {
                    model.IsSelected = false;
                }

                Models.Add(model);
            }
            ViewBag.RoleId = roleId;
            return View(Models);

       }

        [HttpPost]
        public async Task<IActionResult> EditUsersRole(List<EditUsersRoleViewModel> model, string roleId)
        {
            if (string.IsNullOrEmpty(roleId))
            {
                return View("../Error/NotFound", $"The role must be exist and not empty in Url");

            }
            var role = await this._roleManager.FindByIdAsync(roleId);
            if (role is null)
            {
                return View("../Error/NotFound", $"The role Id : {role.Id} cannot be found");
            }

            // role if deja affectté et in model is select il faut le supprimer , ou l'affecté si il est selecté au model mais non affecté before

            IdentityResult result = null;

            for (int i = 0; i < model.Count; i++)
            {
                IdentityUser user = await _userManager.FindByIdAsync(model[i].UserId);

                if (await _userManager.IsInRoleAsync(user, role.Name) && !model[i].IsSelected)
                {
                    result = await _userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else if (!(await _userManager.IsInRoleAsync(user, role.Name)) && model[i].IsSelected)
                {
                    result = await _userManager.AddToRoleAsync(user, role.Name);
                }
            }

            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

            }
            return RedirectToAction("Edit", new { id = roleId });

        }


    }
}

ReservationApp/ReservationApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReservationApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!-- Vendor CSS Files -->
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/assets/css/style.css" rel="stylesheet" />

</head>
<body class="mb-0">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-0" >
            <div class="container">
                <h1 class="navbar-brand">Reservation</h1>
                @*<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>*@
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @*<ul class="nav-menu d-none d-lg-block">*@
                        @if(User.IsInRole("Admin"))
                        {
                            <li class="list-unstyled nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                            </li>
                            <li class="list-unstyled  nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TypeReservations" asp-action="Index">Type Reservations</a>
                            </li>
                            <li class="list-unstyled  nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">Reservations</a>
                            </li>
                        } @if(User.IsInRole("Student"))
                        {
                            <li class="list-unstyled  nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">Reservations</a>
                            </li>

                        }

                    @*</ul>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>

    <!-- ======= Footer ======= -->
    <footer id="footer" class="fixed-bottom">
        <div class="">
            <div class="copyright">
                &copy; Copyright <strong><a class="text-info" href="https://www.youcode.ma/">YouCode.ma</a></strong>
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/kelly-free-bootstrap-cv-resume-html-template/ -->
                Designed by <strong><span>Jihad</span></strong>
</div>
        </div>
    </footer><!-- End  Footer -->
    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - ReservationApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    <!-- Vendor JS Files -->
    <script src="assets/vendor/jquery/jquery.min.js"></script>
    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="assets/vendor/php-email-form/validate.js"></script>
    <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="assets/vendor/counterup/counterup.min.js"></script>
    <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="assets/vendor/venobox/venobox.min.js"></script>
    <script src="assets/vendor/aos/aos.js"></script>

    <!-- Template Main JS File -->
    <script src="assets/js/main.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>